# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ccm.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CCMTask(object):
    def setupUi(self, CCMTask):
        CCMTask.setObjectName("CCMTask")
        CCMTask.resize(712, 585)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CCMTask.sizePolicy().hasHeightForWidth())
        CCMTask.setSizePolicy(sizePolicy)
        CCMTask.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(CCMTask)
        self.centralwidget.setObjectName("centralwidget")
        self.issueBox = QtWidgets.QGroupBox(self.centralwidget)
        self.issueBox.setGeometry(QtCore.QRect(10, 110, 691, 55))
        self.issueBox.setObjectName("issueBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.issueBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ARDTSEdit = QtWidgets.QLineEdit(self.issueBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ARDTSEdit.sizePolicy().hasHeightForWidth())
        self.ARDTSEdit.setSizePolicy(sizePolicy)
        self.ARDTSEdit.setTabletTracking(True)
        self.ARDTSEdit.setObjectName("ARDTSEdit")
        self.horizontalLayout_3.addWidget(self.ARDTSEdit)
        spacerItem = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.issueInfoEdit = QtWidgets.QLineEdit(self.issueBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.issueInfoEdit.sizePolicy().hasHeightForWidth())
        self.issueInfoEdit.setSizePolicy(sizePolicy)
        self.issueInfoEdit.setTabletTracking(True)
        self.issueInfoEdit.setObjectName("issueInfoEdit")
        self.horizontalLayout_3.addWidget(self.issueInfoEdit)
        self.label = QtWidgets.QLabel(self.issueBox)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.issueDetailBox = QtWidgets.QGroupBox(self.centralwidget)
        self.issueDetailBox.setGeometry(QtCore.QRect(10, 170, 691, 401))
        self.issueDetailBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.issueDetailBox.setTabletTracking(True)
        self.issueDetailBox.setObjectName("issueDetailBox")
        self.deletedParamsBox = QtWidgets.QGroupBox(self.issueDetailBox)
        self.deletedParamsBox.setGeometry(QtCore.QRect(500, 20, 161, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deletedParamsBox.sizePolicy().hasHeightForWidth())
        self.deletedParamsBox.setSizePolicy(sizePolicy)
        self.deletedParamsBox.setObjectName("deletedParamsBox")
        self.deletedParamsEdit = QtWidgets.QTextEdit(self.deletedParamsBox)
        self.deletedParamsEdit.setGeometry(QtCore.QRect(10, 20, 141, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deletedParamsEdit.sizePolicy().hasHeightForWidth())
        self.deletedParamsEdit.setSizePolicy(sizePolicy)
        self.deletedParamsEdit.setObjectName("deletedParamsEdit")
        self.opkeysBox_2 = QtWidgets.QGroupBox(self.issueDetailBox)
        self.opkeysBox_2.setGeometry(QtCore.QRect(10, 210, 153, 182))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opkeysBox_2.sizePolicy().hasHeightForWidth())
        self.opkeysBox_2.setSizePolicy(sizePolicy)
        self.opkeysBox_2.setObjectName("opkeysBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.opkeysBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.opkey1Edit_2 = QtWidgets.QLineEdit(self.opkeysBox_2)
        self.opkey1Edit_2.setTabletTracking(True)
        self.opkey1Edit_2.setText("")
        self.opkey1Edit_2.setPlaceholderText("")
        self.opkey1Edit_2.setObjectName("opkey1Edit_2")
        self.verticalLayout_2.addWidget(self.opkey1Edit_2)
        self.opkey2Edit_2 = QtWidgets.QLineEdit(self.opkeysBox_2)
        self.opkey2Edit_2.setTabletTracking(True)
        self.opkey2Edit_2.setText("")
        self.opkey2Edit_2.setPlaceholderText("")
        self.opkey2Edit_2.setObjectName("opkey2Edit_2")
        self.verticalLayout_2.addWidget(self.opkey2Edit_2)
        self.opkey3Edit_2 = QtWidgets.QLineEdit(self.opkeysBox_2)
        self.opkey3Edit_2.setTabletTracking(True)
        self.opkey3Edit_2.setText("")
        self.opkey3Edit_2.setPlaceholderText("")
        self.opkey3Edit_2.setObjectName("opkey3Edit_2")
        self.verticalLayout_2.addWidget(self.opkey3Edit_2)
        self.opkey4Edit_2 = QtWidgets.QLineEdit(self.opkeysBox_2)
        self.opkey4Edit_2.setTabletTracking(True)
        self.opkey4Edit_2.setText("")
        self.opkey4Edit_2.setPlaceholderText("")
        self.opkey4Edit_2.setObjectName("opkey4Edit_2")
        self.verticalLayout_2.addWidget(self.opkey4Edit_2)
        self.opkey5Edit_2 = QtWidgets.QLineEdit(self.opkeysBox_2)
        self.opkey5Edit_2.setTabletTracking(True)
        self.opkey5Edit_2.setText("")
        self.opkey5Edit_2.setPlaceholderText("")
        self.opkey5Edit_2.setObjectName("opkey5Edit_2")
        self.verticalLayout_2.addWidget(self.opkey5Edit_2)
        self.opkey6Edit_2 = QtWidgets.QLineEdit(self.opkeysBox_2)
        self.opkey6Edit_2.setTabletTracking(True)
        self.opkey6Edit_2.setText("")
        self.opkey6Edit_2.setPlaceholderText("")
        self.opkey6Edit_2.setClearButtonEnabled(False)
        self.opkey6Edit_2.setObjectName("opkey6Edit_2")
        self.verticalLayout_2.addWidget(self.opkey6Edit_2)
        self.splitter_2 = QtWidgets.QSplitter(self.issueDetailBox)
        self.splitter_2.setGeometry(QtCore.QRect(10, 20, 153, 182))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.opkeysBox = QtWidgets.QGroupBox(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opkeysBox.sizePolicy().hasHeightForWidth())
        self.opkeysBox.setSizePolicy(sizePolicy)
        self.opkeysBox.setObjectName("opkeysBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.opkeysBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.opkey1Edit = QtWidgets.QLineEdit(self.opkeysBox)
        self.opkey1Edit.setTabletTracking(True)
        self.opkey1Edit.setText("")
        self.opkey1Edit.setObjectName("opkey1Edit")
        self.verticalLayout.addWidget(self.opkey1Edit)
        self.opkey2Edit = QtWidgets.QLineEdit(self.opkeysBox)
        self.opkey2Edit.setTabletTracking(True)
        self.opkey2Edit.setText("")
        self.opkey2Edit.setObjectName("opkey2Edit")
        self.verticalLayout.addWidget(self.opkey2Edit)
        self.opkey3Edit = QtWidgets.QLineEdit(self.opkeysBox)
        self.opkey3Edit.setTabletTracking(True)
        self.opkey3Edit.setText("")
        self.opkey3Edit.setObjectName("opkey3Edit")
        self.verticalLayout.addWidget(self.opkey3Edit)
        self.opkey4Edit = QtWidgets.QLineEdit(self.opkeysBox)
        self.opkey4Edit.setTabletTracking(True)
        self.opkey4Edit.setText("")
        self.opkey4Edit.setObjectName("opkey4Edit")
        self.verticalLayout.addWidget(self.opkey4Edit)
        self.opkey5Edit = QtWidgets.QLineEdit(self.opkeysBox)
        self.opkey5Edit.setTabletTracking(True)
        self.opkey5Edit.setText("")
        self.opkey5Edit.setObjectName("opkey5Edit")
        self.verticalLayout.addWidget(self.opkey5Edit)
        self.opkey6Edit = QtWidgets.QLineEdit(self.opkeysBox)
        self.opkey6Edit.setTabletTracking(True)
        self.opkey6Edit.setText("")
        self.opkey6Edit.setClearButtonEnabled(False)
        self.opkey6Edit.setObjectName("opkey6Edit")
        self.verticalLayout.addWidget(self.opkey6Edit)
        self.splitter = QtWidgets.QSplitter(self.issueDetailBox)
        self.splitter.setGeometry(QtCore.QRect(190, 20, 291, 361))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.newParamsBox = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newParamsBox.sizePolicy().hasHeightForWidth())
        self.newParamsBox.setSizePolicy(sizePolicy)
        self.newParamsBox.setObjectName("newParamsBox")
        self.newParamsEdit = QtWidgets.QTextEdit(self.newParamsBox)
        self.newParamsEdit.setGeometry(QtCore.QRect(10, 20, 271, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newParamsEdit.sizePolicy().hasHeightForWidth())
        self.newParamsEdit.setSizePolicy(sizePolicy)
        self.newParamsEdit.setPlaceholderText("")
        self.newParamsEdit.setObjectName("newParamsEdit")
        self.modifiedParamsBox = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modifiedParamsBox.sizePolicy().hasHeightForWidth())
        self.modifiedParamsBox.setSizePolicy(sizePolicy)
        self.modifiedParamsBox.setObjectName("modifiedParamsBox")
        self.modifiedParamsEdit = QtWidgets.QTextEdit(self.modifiedParamsBox)
        self.modifiedParamsEdit.setGeometry(QtCore.QRect(10, 20, 271, 121))
        self.modifiedParamsEdit.setObjectName("modifiedParamsEdit")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(22, 20, 661, 81))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.branchSelectBox = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.branchSelectBox.sizePolicy().hasHeightForWidth())
        self.branchSelectBox.setSizePolicy(sizePolicy)
        self.branchSelectBox.setObjectName("branchSelectBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.branchSelectBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox10x = QtWidgets.QCheckBox(self.branchSelectBox)
        self.checkBox10x.setChecked(True)
        self.checkBox10x.setObjectName("checkBox10x")
        self.horizontalLayout_4.addWidget(self.checkBox10x)
        self.checkBox9x = QtWidgets.QCheckBox(self.branchSelectBox)
        self.checkBox9x.setChecked(True)
        self.checkBox9x.setObjectName("checkBox9x")
        self.horizontalLayout_4.addWidget(self.checkBox9x)
        self.horizontalLayout.addWidget(self.branchSelectBox)
        spacerItem1 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.startButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.startButton.setFont(font)
        self.startButton.setWhatsThis("")
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        CCMTask.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CCMTask)
        self.statusbar.setObjectName("statusbar")
        CCMTask.setStatusBar(self.statusbar)

        self.retranslateUi(CCMTask)
        QtCore.QMetaObject.connectSlotsByName(CCMTask)

    def retranslateUi(self, CCMTask):
        _translate = QtCore.QCoreApplication.translate
        CCMTask.setWindowTitle(_translate("CCMTask", "CCMTask"))
        self.issueBox.setTitle(_translate("CCMTask", "需求信息"))
        self.ARDTSEdit.setPlaceholderText(_translate("CCMTask", "AR或者DTS编号"))
        self.issueInfoEdit.setPlaceholderText(_translate("CCMTask", "需求描述信息"))
        self.issueDetailBox.setTitle(_translate("CCMTask", "需求内容"))
        self.deletedParamsBox.setTitle(_translate("CCMTask", "删除参数"))
        self.opkeysBox_2.setTitle(_translate("CCMTask", "审核人列表"))
        self.opkeysBox.setTitle(_translate("CCMTask", "运营商列表"))
        self.opkey1Edit.setPlaceholderText(_translate("CCMTask", "OPkey1"))
        self.opkey2Edit.setPlaceholderText(_translate("CCMTask", "OPkey2"))
        self.opkey3Edit.setPlaceholderText(_translate("CCMTask", "OPkey3"))
        self.opkey4Edit.setPlaceholderText(_translate("CCMTask", "OPkey4"))
        self.opkey5Edit.setPlaceholderText(_translate("CCMTask", "OPkey5"))
        self.opkey6Edit.setPlaceholderText(_translate("CCMTask", "OPkey6"))
        self.newParamsBox.setTitle(_translate("CCMTask", "新增参数"))
        self.modifiedParamsBox.setTitle(_translate("CCMTask", "修改参数"))
        self.branchSelectBox.setTitle(_translate("CCMTask", "分支选择"))
        self.checkBox10x.setText(_translate("CCMTask", "10.x ALL"))
        self.checkBox9x.setText(_translate("CCMTask", "9.x ALL"))
        self.startButton.setText(_translate("CCMTask", "Start"))
